---
# setup my macbook just the way I like it

-   hosts: mac
    roles:
        -   role: homebrew
            applications:
                - awscli
                - tmux
                - htop
                - terraform
                - php@7.2
                - q
                - jq
                - yarn
                - hub
                - make
                - miller
                - qemu
                # Coreutils adds realpath among other things
                - coreutils
                - docker-credential-helper-ecr
                - zsh
                - zsh-completions
                - airplanedev/tap/airplane
            casks:
                - 1password
                - 1password-cli
                - discord
                - devutils
                - docker
                - firefox
                - google-chrome
                - jetbrains-toolbox
                - libreoffice
                - microsoft-auto-update
                - microsoft-excel
                - microsoft-word
                - loom
                - ngrok
                - pop
                - postman
                - slack
                - spectacle
                - spotify
                - zoom

        -   role: ssh-keys
            github_key_title: "mbp.14-inch-retina-2021"
        -   role: karlmdavis.rcm-dotfiles
            rcm_user: "{{ lookup('env', 'USER') }}"
            rcup_bin: /usr/local/bin/rcup
            rcm_repos:
                -   repo: 'git@github.com:tomtomau/dotfiles.git'
                    dest: "{{ lookup('env', 'HOME') }}/.dotfiles/"
        -   role: use-zsh
        -   role: suzuki-shunsuke.nvm
            nvm_rc_path: "{{ ansible_env.HOME }}/.zsh"

